spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lobster
    username: lobster
    password: 1234
  webflux:
    cors:
      enabled: true
      allowed-origins: http://localhost:3000
      allowed-methods: GET, POST, PUT, DELETE
      allowed-headers: Content-Type, Authorization
  mail:
    host: smtp.naver.com
    port: 465
    username: lobster_team@naver.com
    password: givemelobster!!
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbm
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true
        format_sql: 'true'

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  password: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa


server:
  port: 8080



